Upgrade Apache Tika in wrapper to v2.3.0 (was 2.2.1)
Note that 3 packages (org.w3c.dom, org.xml.sax and org.xml.sax.helpers)
were added to the imported packages of the plug-in to take care of the
following classloader-related issue:

java.lang.LinkageError: loader constraint violation for class
org.apache.xerces.jaxp.DocumentBuilderImpl: when selecting overriding
method org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Lorg/xml/sax/InputSource;)Lorg/w3c/dom/Document;
the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader
@684be7b5 (instance of
org.eclipse.osgi.internal.loader.EquinoxClassLoader, child of 'platform'
jdk.internal.loader.ClassLoaders$PlatformClassLoader) of the selected
method's type org.apache.xerces.jaxp.DocumentBuilderImpl, and the class
loader 'bootstrap' for its super type javax.xml.parsers.DocumentBuilder
have different Class objects for the type org.xml.sax.InputSource used
in the signature