Fix import error with area call procedures (dictionary only)
The error is 'Error while importing schema:
java.lang.IllegalArgumentException: No enum constant
org.lh.dmlj.schema.AreaProcedureCallFunciton.finish'.

Apparently we were also missing the simple READY option (so without any
further specification).